---
- name: Assert platform is supported
  tags: php
  assert:
    that:
      - ansible_os_family in ['Debian']

- include_vars: "{{ ansible_os_family }}.yml"
  tags: php

# Include os-specific tasks
- include: "Debian.yml"
  tags: php
  when: ansible_os_family == 'Debian'

- name: Install PHP 
  tags: php
  action: "{{ ansible_pkg_mgr }} state=latest name={{ item }}"
  with_items:
    - "{{ php_package_list }}"
    - "{{ php_package_list_additional }}"

- name: check mods-available dir exists
  tags: php
  register: mods_exists
  stat:
    path="{{ php_mods_dir }}"


- name: Install PHP Configuration
  tags: php
  ini_file: 
    dest="{% if mods_exists.stat.exists %}{{ php_mods_dir }}{% else %}{{ php_confd }}{% endif %}/{{ php_config_changes_ini }}" 
    section="{{ item.section }}" 
    option="{{ item.option }}" 
    value="{{ item.value }}" 
  with_items: php_config

- name: Install submodule config
  tags: php
  ini_file: 
    dest="{% if mods_exists.stat.exists %}{{ php_mods_dir }}{% else %}{{ php_confd }}{% endif %}/{{item.0.name}}.ini" 
    section="{{ item.1.section }}"  
    option="{{ item.1.option }}" 
    value="{{ item.1.value }}"
  with_subelements:
    - php_modules_conf
    - configs

- name: Use php5enmod if exists
  tags: php
  with_items: php_mods_enabled
  when: mods_exists.stat.exists 
  command: php5enmod {{ item }}

