---
- name: Assert platform is supported
  tags: php
  assert:
    that:
      - ansible_os_family in ['Debian']

- include_vars: "{{ ansible_os_family }}.yml"
  tags: php

# Include os-specific tasks
- include: "Debian.yml"
  tags: php
  when: ansible_os_family == 'Debian'

- name: Install PHP 
  tags: php
  action: "{{ ansible_pkg_mgr }} state=latest name={{ item }}"
  with_items:
    - "{{ php_package_list }}"
    - "{{ php_package_list_additional }}"

- name: Install PHP Configuration
  tags: php
  ini_file: 
    dest="{{ php_confd }}/{{ php_config_changes_ini }}" 
    section="{{ item.section }}" 
    option="{{ item.option }}" 
    value="{{ item.value }}" 
  with_items: php_config

- name: Remove submodule configs if new config is given
  tags: php
  file: path="{{ php_confd }}/{{item.name}}.ini" state=absent
  with_items: php_modules_conf

- name: Install submodule config
  tags: php
  ini_file: 
    dest="{{ php_confd }}/{{item.0.name}}.ini" 
    section="{{ item.1.section }}"  
    option="{{ item.1.option }}" 
    value="{{ item.1.value }}"
  with_subelements:
    - php_modules_conf
    - configs
