---
- name: Assert platform is supported
  tags: php
  assert:
    that:
      - ansible_os_family in ['Debian','RedHat']


- name: Include OS specific configuration
  tags: php
  include: "{{ php_path_to_lib_role }}/silpion.lib/tasks/os-specific-vars.yml"

# Include os-specific tasks
- name: Include Ubuntu specific tasks
  tags: php
  when: ansible_distribution == 'Ubuntu' and php_ppa is defined
  include: "Ubuntu.yml"

- name: Install PHP
  tags: php
  become: true
  with_items:
    - "{{ php_package_list }}"
    - "{{ php_package_list_additional }}"
  action: "{{ ansible_pkg_mgr }}"
  args:
    state: "{{ util_package_state|default('installed') }}"
    name: "{{ item }}"

- name: Install crudini with pip
  tags: php
  become: true
  pip:
    name: crudini

- name: Check command php5enmod exists
  tags: php
  register: php_register_mods_exists
  check_mode: false
  failed_when: false
  changed_when: false
  shell: 'command -v {{ php_en_mod }}'

- name: Decide Modules config-dir
  tags: php
  set_fact:
    php_fact_mods_dir: "{{ php_mods_dir if php_register_mods_exists.stdout else php_confd }}"

- name: Install PHP configuration
  tags: php
  become: true
  with_items: "{{ php_config }}"
  ini_file:
    dest: "{{ php_fact_mods_dir }}/{{ php_config_changes_ini|regex_replace('.ini$', '') }}.ini"
    section: "{{ item.section|default(php_default_ini_section) }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"

- name: Register existing module ini-files
  tags: php
  with_items: "{{ php_modules_conf }}"
  register: php_register_mods_ini
  stat:
    path: "{{ php_fact_mods_dir }}/{{ item.name }}.ini"

# Use commandline tool crudini to move any configuration from DEFAULT section into module section.
# This is necessary to allow ansible ini_file: module to work with existing ini files.
- name: Fix php module ini-files and remove DEFAULT section
  tags: php
  become: true
  with_items: "{{ php_register_mods_ini.results }}"
  when: php_register_mods_ini.results is defined and item.stat.exists
  shell:
    crudini --set {{ item.item.name }}.ini {{ item.item.name }};
    crudini --merge --existing  {{ item.item.name }}.ini  {{ item.item.name }} < {{ item.item.name }}.ini;
    crudini --del {{ item.item.name }}.ini DEFAULT
  args:
    chdir: "{{ php_fact_mods_dir }}"

- name: Install submodule configuration
  tags: php
  become: true
  with_subelements:
    - "{{ php_modules_conf }}"
    - configs
  ini_file:
    dest: "{{ php_fact_mods_dir }}/{{ item.0.name }}.ini"
    section: "{{ item.1.section }}"
    option: "{{ item.1.option }}"
    value: "{{ item.1.value }}"

- name: Use {{ php_en_mod }} to enable modules
  tags: php
  become: true
  changed_when: false
  with_items: "{{ php_mods_enabled + [ php_config_changes_ini|regex_replace('.ini$', '') ]}}"
  when: php_register_mods_exists.stdout != ''
  command: "{{ php_en_mod }} {{ item }}"

- name: Use {{ php_dis_mod }} to disable modules
  tags: php
  become: true
  changed_when: false
  with_items: "{{ php_mods_disabled }}"
  when: php_register_mods_exists.stdout != ''
  command: "{{ php_dis_mod }} {{ item }}"

# Install role facts
#   This should be the last tasks in main.yml.
#   Add any other tasks above this one, if applicable.
- name: Include facts management
  tags:
    - php
    - facts
    - localfacts
  include: "{{ php_path_to_lib_role }}/silpion.lib/tasks/localfacts.yml"
  vars:
    namespace: php
